name: hrrr-zarr
channels:
   - conda-forge
dependencies:
   - python=3.10.4 
   - xarray=2022.3.0
   - cartopy=0.20.2
   - metpy=1.3.0
   - boto3=1.23.10
   - zarr=2.11.3
   - s3fs=0.4.2
   - matplotlib=3.5.2
   - ipykernel=6.13.0
   - dask=2022.5.2 
